_reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
_reference_os: &reference_os
  'linux'

language: bash

git:
  depth: false
  autocrlf: input

os:
  - osx
  - windows
  - *reference_os
addons:
  apt:
    packages:
      - graphviz

stages:
  - check
  - test
  - name: deploy
    if: type != pull_request AND repo = DanySK/java-quadtree

env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@"
    - JDK="adopt-openj9@"

jobs:
  exclude:
    - os: *reference_os
      env: *reference_jdk
      stage: test
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
    - stage: deploy
      name: "Reports and deployment"
      os: *reference_os
      env:
        - PUBLISH="true"
        # Signing
        - secure: "R0RY3PuASK/Ej7CZTX/1e1GKNqHPVX6c5Im2++E7lbVqa5xudwETD7tkWKqCdIDWnbSrcrPIlCNkbu7inL/mCaKC3092nAX5ijBseF1SkxK9971tol7fVLiDh14X+B9+OtW1rJveT3oIERbsEs3/fdKRbsXHknDZp54HrgPuKpQ0jUk8RUEYBwXdNgplMZCLSsJdvM7d9natXTqf4QKiCA/fS5MU8rfPDypFjOeNypECbnLdzswyaZ/lpTt7/mKyPUdjcYkFEEPgi+WS9HuIDqJWa20z/geBaiQLA+Rj5AJF765Yx2oUpFCFSAuk75ZFETTnFRYdQikPJs0Jry3iELLSwqZU73TJWzKhZZar6qJMxUTQy+Kzt6yCuAmp0q/SkT5eepJp3pHO9cegJrQ52lEgH8+7LMA2aP9ZFqMloh2WUJGALX2EHVwgxyy2dNOp4nvHvVEJ9XEFuYEruNtri7kTNv67v2yoGDr5wz4whnBIZ84/T0EyqRKRjq3kR+RyQm1C2O5/19kuz9ppSmTBfPNfjfC/G7GwgOSPWinxQPzWf+szQypZ4+YItNyWkNogOKbC6O6AY/tTP0LUhxUEKOS+uBboc/9cbgQ1sdwx8CaUT4sbmpsGbS0Z6dTE0EqgMP0Ip7j4iW+nOycvUpDDWE9D7Soq6AcSSUTMf6zdlDU="
        # Central
        - secure: "kZnJBCZLaRbvs2EZNM/n/z29gapLCtOa64pQ8KVI9ITWCMm/9niVrcxC8pm1t46MgOmzF8WD74+i826xPuc2IitL8m9DVJjl54/0RgpM7frDwesGwPNIGUSOrR6qjIDDwliCqX0EI8XfJttJhE+KqoYs9rGvcTOqoASwCsI3srY2DsKZXZlpJgJ+Q1mqizfjfXtaxqo+S+VgrID60Nw4H2+UoQYQCTmcH6HYZu4aRbRwyH03Z4APpxuz1wMbY2WREMdL65NeBJ1Hn6UM09pTpgtic9Xj+QPqZb/KgrCH+7YUh3Ioa0z4+Ri13a8lCZaUKhTdoAKCi3L0oYPa6c8u9Evj4H64lbkD/PQm1wREFiHyovsadB0bx4biD74l2uxxvFbtAegksX3stEGJr67Rc5Bc7DyCd2qkh1389+iQ9sqtMf5bavZjSM29oGAqcOhx8sYOzg2PzIcTtaLWK2io4PeIRiyDw9Fpsorj8vJyzFRoncFK/Un1PO/4HHZwk1FJ3XNDSzgRxHng/ljAnsrMnrq3bdjix4Tqwo1WgrG/00/L1VZVhpJ8dE7572YmbxahD5eO2EXWqk1zbMc+xe5gVaecuVkg5ab356zIafkjaUDhZ+N0HUkuQFlF+rGIf8T8G4M8jn6s037j4adJ4Mk5bimhJEfaWSnYrVKQ4i0YQMc="
        - secure: "JVoQ1NHBe26KNVrRHOWVY3MzIdqsnbz/uZTP+9TEx15FQ5yVyk8prKB0SyLoYwz70cE2g/2W+Ix5fVtp8ZpOeZ/ONpJgo8abqxKHkuWsOd6rUSFwe9FpnCgaiMDqH4mhUxv3llrCWugAoBoNSfbjDqy2/X0kyGPdmRHu7XFTAsHJcZeG4KFjuLU+v4W6NrlsDm4vwiJ4iitybI5cggxoR4KU6mccst4vIFhOcnpBx5ERJxATGEgJv0mTubM24H2SiKcxCW3HY8DMuwEVNjCt+d+3rWvDem+EjrFMQ+RxJ/OJwG4fo/B1GDuI+klJB5S3CP2HSlG3jReRHkL4qHRU1Hj2pw5OsKkBBovxMmjFv6vF5VGSZ3FBQhR8rzDMMN+YwHLFxrTH08Ikjqw2CoxBw+wq146fsz0/Vkdoird39O0iz0Wo2RLbkwzM9IEyqFBITnxEQ5Uq33q+1ivpFihO+hRlFQXOh1EZLCT8RIqpyCYxxDzX4h5tlkqVdPGQ9/LX2bb9kTviCggJeBy0gjVt/iXEywMMTxXpPi4MtgS4Sg58wys93H6IQk3gTBRdeD6TJYPJ0kFy2YSmf5OnTX6XarMFD6hQ7NiCtC1Dy57toOVSjUygrIdr/tuc2tM2sVr0a0bakXptkhHCj9GMdmrycdg7+w+tHiWorOOxy8f9G3c="
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_ff8e67061518_key -iv $encrypted_ff8e67061518_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - travis_retry ./gradlew publishAll

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script:
  - travis_retry ./gradlew check

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
