[libraries]
junit4 = "junit:junit:4.13.2"

[plugins]
dokka = "org.jetbrains.dokka:2.1.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.11"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.97.0"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.3.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.2"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.12"
taskTree = "com.dorongold.task-tree:4.0.1"
