[libraries]
junit4 = "junit:junit:4.13.2"

[plugins]
dokka = "org.jetbrains.dokka:2.1.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.6"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.95.3"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.2.21"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.1"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.7"
taskTree = "com.dorongold.task-tree:4.0.1"
