[libraries]
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.8.6"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:3.1.7"
java-qa = "org.danilopianini.gradle-java-qa:1.87.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:3.2.1"
publishOnCentral = "org.danilopianini.publish-on-central:8.0.2"
taskTree = "com.dorongold.task-tree:4.0.0"
