[libraries]
junit4 = "junit:junit:4.13.2"

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.4"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.95.1"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.2.20"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.1.2"
publishOnCentral = "org.danilopianini.publish-on-central:9.1.5"
taskTree = "com.dorongold.task-tree:4.0.1"
