[libraries]
guava = "com.google.guava:guava:31.0.1-jre"
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.5.2"

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:0.3.0"
java-qa = "org.danilopianini.gradle-java-qa:0.13.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.3.1"
publishOnCentral = "org.danilopianini.publish-on-central:0.7.7"
taskTree = "com.dorongold.task-tree:2.1.0"
