[libraries]
guava = "com.google.guava:guava:32.1.3-jre"
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.8.3"

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:2.0.5"
java-qa = "org.danilopianini.gradle-java-qa:0.44.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.7"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.20"
taskTree = "com.dorongold.task-tree:2.1.1"
