[libraries]
junit4 = "junit:junit:4.13.2"

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:4.0.2"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.85.0"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.1.20"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:3.3.0"
publishOnCentral = "org.danilopianini.publish-on-central:8.0.6"
taskTree = "com.dorongold.task-tree:4.0.1"
