[libraries]
guava = "com.google.guava:guava:33.3.1-jre"
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.8.6"

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:3.1.7"
java-qa = "org.danilopianini.gradle-java-qa:1.68.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:1.2.8"
publishOnCentral = "org.danilopianini.publish-on-central:5.1.8"
taskTree = "com.dorongold.task-tree:4.0.0"
