[libraries]
guava = "com.google.guava:guava:32.1.2-jre"
junit4 = "junit:junit:4.13.2"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.7.3"

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:1.1.10"
java-qa = "org.danilopianini.gradle-java-qa:0.44.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.4"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.11"
taskTree = "com.dorongold.task-tree:2.1.1"
